# Generated by Django 5.0.1 on 2024-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amigo',
            options={'managed': True},
        ),
    ]
