# Generated by Django 5.0.1 on 2024-02-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_amigo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='id_amigo',
            field=models.ForeignKey(blank=True, db_column='id_amigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='amigo_id_amigo_set', to='pokemon.usuario'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon.usuario'),
        ),
    ]
